services:
  postgres:
    image: postgres:17.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  bq-logs-django:
    build: ./brandquad_backend_test_task
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./.env

volumes:
  postgres_data:
